apiVersion: apps/v1
kind: Deployment
metadata:
    name: deliverit-front-dealer-deployment
    labels:
        app: deliverit-front-dealer
spec:
    replicas: 1
    selector:
        matchLabels:
            app: deliverit-front-dealer
    template:
        metadata:
            labels:
                app: deliverit-front-dealer
        spec:
            containers:
                - name: deliverit-front-dealer
                  image: 913891584254.dkr.ecr.sa-east-1.amazonaws.com/deliverit-front-dealer:latest
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 3000