apiVersion: v1
kind: Service
metadata:
    name: deliverit-front-dealer-service
spec:
    selector:
        app: deliverit-front-dealer
    type: ClusterIP
    ports:
        - protocol: TCP
          port: 80
          targetPort: 3000