import React from 'react';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
const poppins = Poppins({
    subsets: ['latin-ext'],
    weight: ['400', '500', '600', '700'],
});

import 'tailwindcss/tailwind.css';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en'>
            <body className={poppins.className}>{children}</body>
        </html>
    );
}
